#ifndef KEYBOARD_H
#define KEYBOARD_H
//https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes


#define KEYBOARD_KEY_A 0x41
#define KEYBOARD_KEY_B 0x42
#define KEYBOARD_KEY_C 0x43
#define KEYBOARD_KEY_D 0x44
#define KEYBOARD_KEY_E 0x45
#define KEYBOARD_KEY_F 0x46
#define KEYBOARD_KEY_G 0x47
#define KEYBOARD_KEY_H 0x48
#define KEYBOARD_KEY_I 0x49
#define KEYBOARD_KEY_J 0x4A
#define KEYBOARD_KEY_K 0x4B
#define KEYBOARD_KEY_L 0x4C
#define KEYBOARD_KEY_M 0x4D
#define KEYBOARD_KEY_N 0x4E
#define KEYBOARD_KEY_O 0x4F
#define KEYBOARD_KEY_P 0x50
#define KEYBOARD_KEY_Q 0x51
#define KEYBOARD_KEY_R 0x52
#define KEYBOARD_KEY_S 0x53
#define KEYBOARD_KEY_T 0x54
#define KEYBOARD_KEY_U 0x55
#define KEYBOARD_KEY_V 0x56
#define KEYBOARD_KEY_W 0x57
#define KEYBOARD_KEY_X 0x58
#define KEYBOARD_KEY_Y 0x59
#define KEYBOARD_KEY_Z 0x5A
#define KEYBOARD_KEY_WIN_LEFT 0x5B
#define KEYBOARD_KEY_WIN_RIGHT 0x5C

#define KEYBOARD_KEY_SPACE 0x20

#define KEYBOARD_KEY_1 0x31
#define KEYBOARD_KEY_2 0x32
#define KEYBOARD_KEY_3 0x33
#define KEYBOARD_KEY_4 0x34
#define KEYBOARD_KEY_5 0x35
#define KEYBOARD_KEY_6 0x36
#define KEYBOARD_KEY_7 0x37
#define KEYBOARD_KEY_8 0x38
#define KEYBOARD_KEY_9 0x39

#define KEYBOARD_KEY_ENTER 0x0D


#endif // KEYBOARD_H
